.TH Servidor ServidorPokemon
.SH NAME: ServidorPokemon
.SH SYNOPSIS
Programa que simula un servidor con el cual se aceptaran multiples conexiones
a traves de hilos.
.br
.PP
.B getBytes(n)
.SH Description
.PP
n - Entero
.br
Funcion que nos regresa una lista con los 4 bytes que conforman el entero n
.br
Se convierte el entero n en una cadena de 32 bits y se dan los 4 bytes que lo conforman.
.br
.PP
.B inicio()
.SH Description
.br
Funcion para iniciar las conexiones
.B updatePokedex
.PP
usuario
.br
pokemon

